name: build_scripts Publish Docs
on:
  push:
    branches:
      - main

    paths:
      - blog/**
      - docs/**
      - build_scripts/**
      - .github/workflows/publish_docs_f25e.yaml
      - mkdocs.yml

jobs:
  build:
    environment: main
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          token_format: 'access_token'
          workload_identity_provider: projects/144266375356/locations/global/workloadIdentityPools/scs-pool/providers/gh-provider
          service_account: artifacts-scs-rw@cognite-inso-internal.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Setup artifactory auth
        run: gcloud auth configure-docker europe-docker.pkg.dev #

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.1

      - name: Install keyrings backend plugin to poetry
        run: poetry self add keyrings.google-artifactregistry-auth

      - name: Install poetry dependencies for the build
        run: poetry install --sync

      - name: Install pack
        uses: buildpacks/github-actions/setup-pack@v5.1.0

      - run: echo "version=$(date -u '+%Y%m%dT%H%M%SZ')"  >> $GITHUB_ENV

      - run: chmod +x ./build_scripts/build_docs.sh && build_scripts/build_docs.sh # Set chmod as I got build_scripts/build_docs.sh: Permission denied
        env:
          PUBLISH: true
          VERSION: ${{ env.version }}
          IMAGE: europe-docker.pkg.dev/cognite-inso-internal/production/neat
